Create every requirement for the project
billymohajeri/Space-Travelers-Hub pull request #42
Opened 2023-02-01 15:54 UTC by billymohajeri

Hi everyone,

We @EddyShimwa and @billymohajeri collaborated on this project. As we were 2 partners, we didn't implement the Team3 sections.

We implemented:

2023-02-01 17:01 UTC, Felix45 requested changes
Hi @billymohajeri & @EddyShimwa , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif" />

## Highlights :heavy_check_mark: 
- [ ] Good UI design :white_check_mark: 
- [ ] Application works as expected :white_check_mark: 
- [ ] Descriptive pull request title and summary :white_check_mark: 
- [ ] Repository has a professional readme file :white_check_mark: 
- [ ] Git flow is used correctly :white_check_mark: 
- [ ] Good descriptive commit messages :white_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 17:01 UTC, Felix45 commented on src/App.test.js
> +});
- [ Required ] It would be better if you added `tests` for all your components and functions as stated in the project requirements. Currently, only the default `App.test.js` is present in your project. Kindly add tests to test all the components and functions.

## Project requirements
![Screenshot from 2023-02-01 19-27-37](https://user-images.githubusercontent.com/16392046/216103754-f0f79050-9cb0-446f-8ba9-bb2b339557c4.png)

2023-02-01 23:25 UTC, BregornOriginal requested changes
## Hi @Team 💯 💯 💯  

## Good job so far!

## There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![one-step-closer-one-more](https://user-images.githubusercontent.com/93630700/216190352-20957c53-e5f4-4793-9c56-2e840c0b59a8.gif)


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-01 23:25 UTC, BregornOriginal commented on src/App.test.js
> +test('renders learn react link', () => {
Good work adding tests as the previous reviewer request 🥇 

- [ ] Kindly fix this test, it's not passing

![image](https://user-images.githubusercontent.com/93630700/216190214-af0bdbd1-763b-4504-86db-483ce750a08c.png)


![image](https://user-images.githubusercontent.com/93630700/216190184-ec642b33-9330-490e-8bc1-57a0872287ea.png)

2023-02-02 07:25 UTC, topeogunleye approved these changes
### Hi Team

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 07:28 UTC, merged